### PR TITLE
waiting on empty queue will freeze Reactive

### PR DESCRIPTION
**Pull request by SimonDanisch**

### CODE REVIEW

**Comment by JobJob** [comment]
Nice, I think I was seeing this.

**Comment by SimonDanisch** [comment]
```Julia
Error :: (line:272) :: every
      Expression: [0.5, 0.5, 0.5] --> roughly(diff(log), atol=0.1)
      error compiling #isapprox#14: error compiling vecnorm: error compiling vecnorm2: could not load library "libopenblas64_"
      dlopen(libopenblas64_.dylib, 1): Library not loaded: /usr/local/opt/gcc@6/lib/gcc/6/libgfortran.3.dylib
        Referenced from: /Users/travis/julia/lib/julia//libopenblas64_.dylib
        Reason: image not found
```
Oh what now?
I guess this isn't about my changes and I can merge?

**Comment by JobJob** [comment]
Definitely looks completely unrelated to your changes. That test uses a `norm` so has a problem when the linalg libs weren't there - see the warnings above that error:
```
WARNING: Error during initialization of module LinAlg:
ErrorException("could not load library "libopenblas64_"
dlopen(libopenblas64_.dylib, 1): Library not loaded: /usr/local/opt/gcc@6/lib/gcc/6/libgfortran.3.dylib
  Referenced from: /Users/travis/julia/lib/julia//libopenblas64_.dylib
  Reason: image not found")
WARNING: Error during initialization of module CHOLMOD:
ErrorException("could not load library "libcholmod"
dlopen(libcholmod.dylib, 1): Library not loaded: /usr/local/opt/gcc@6/lib/gcc/6/libgfortran.3.dylib
  Referenced from: /Users/travis/julia/lib/julia//libopenblas64_.dylib
  Reason: image not found")
```
cc: @tkelman

**Comment by JobJob** [comment]
FYI it works for me on Mac with julia >= 0.5 (including yesterday's master)

**Pull request merged**
