### PR TITLE
Added a default filter method without a value

### LINKED ISSUE #155: Compatibility with Julia v0.6
With Julia v1.0 around the corner, and this being an awesome and must-have package, it would be very cool if it worked with Julia v0.6.
For example:
```julia
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: https://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.6.0 (2017-06-19 13:05 UTC)
 _/ |\__'_|_|_|\__'_|  |  Official http://julialang.org/ release
|__/                   |  x86_64-pc-linux-gnu

julia> using Reactive

julia> x = Signal(0)
1: "input" = 0 Int64 

julia> z = filter(a -> a % 2 == 0, x)
WARNING: filter(flt, itr) is deprecated, use Iterators.filter(flt, itr) instead.
Stacktrace:
 [1] depwarn(::String, ::Symbol) at ./deprecated.jl:70
 [2] filter(::Function, ::Reactive.Signal{Int64}) at ./deprecated.jl:57
 [3] eval(::Module, ::Any) at ./boot.jl:235
 [4] eval_user_input(::Any, ::Base.REPL.REPLBackend) at ./REPL.jl:66
 [5] macro expansion at ./REPL.jl:97 [inlined]
 [6] (::Base.REPL.##1#2{Base.REPL.REPLBackend})() at ./event.jl:73
while loading no file, in expression starting on line 0
Base.Iterators.Filter{##1#2,Reactive.Signal{Int64}}(#1, 1: "input" = 0 Int64 )

julia> foreach(println, z)
ERROR: MethodError: no method matching start(::Reactive.Signal{Int64})
Closest candidates are:
  start(::SimpleVector) at essentials.jl:258
  start(::Base.MethodList) at reflection.jl:560
  start(::ExponentialBackOff) at error.jl:107
  ...
Stacktrace:
 [1] start_filter(::##1#2, ::Reactive.Signal{Int64}) at ./iterators.jl:269
 [2] foreach(::Base.#println, ::Base.Iterators.Filter{##1#2,Reactive.Signal{Int64}}) at ./abstractarray.jl:1731
```

### PR DESCRIPTION
**Pull request by yakir12**
fixes #155

### CODE REVIEW

**Comment by JobJob** [comment]
Thanks!

@tkelman will this be ok in terms of method type piracy if the `::Function` is removed? I'm assuming that will be necessary.

**Comment by tkelman** [comment]
Signal is defined here so as long as you require at least one of those I think you're fine

**Comment by yakir12** [comment]
OK, so I think I understand now (this is mostly a note to myself): the function's signature must be local to avoid piracy. Since `filter` is in a function in `Base.Iterators`, `Function` is a type in `Base`, but `Signal` is not (it's defined in `Reactive`), we accomplish uniqueness by correctly signing one of the `filter`'s arguments with the `Signal` type.

**Comment by JobJob** [comment]
Cheers @tkelman 

Thanks @yakir12 - tests are sexy!

**Pull request merged**
